name: upon_website
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  custom_sliding_segmented_control: ^1.7.5
  animated_text_kit: ^4.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/
