name: upon_site
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.5
  custom_sliding_segmented_control: ^1.7.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  
  image: assets/logo_u.png
  background_image: "assets/background_gradient.png"