name: upon_site
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.5
  custom_sliding_segmented_control: ^1.7.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
